// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=ports_mock.go -package=roaring_bitmaps
//

// Package roaring_bitmaps is a generated GoMock package.
package roaring_bitmaps

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOps is a mock of Ops interface.
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
	isgomock struct{}
}

// MockOpsMockRecorder is the mock recorder for MockOps.
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance.
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// AndCardinality mocks base method.
func (m *MockOps) AndCardinality(a, b []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AndCardinality", a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// AndCardinality indicates an expected call of AndCardinality.
func (mr *MockOpsMockRecorder) AndCardinality(a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AndCardinality", reflect.TypeOf((*MockOps)(nil).AndCardinality), a, b)
}

// AndNotTo mocks base method.
func (m *MockOps) AndNotTo(dst, a, b []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AndNotTo", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// AndNotTo indicates an expected call of AndNotTo.
func (mr *MockOpsMockRecorder) AndNotTo(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AndNotTo", reflect.TypeOf((*MockOps)(nil).AndNotTo), dst, a, b)
}

// AndTo mocks base method.
func (m *MockOps) AndTo(dst, a, b []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AndTo", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// AndTo indicates an expected call of AndTo.
func (mr *MockOpsMockRecorder) AndTo(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AndTo", reflect.TypeOf((*MockOps)(nil).AndTo), dst, a, b)
}

// BitmapToArray mocks base method.
func (m *MockOps) BitmapToArray(dst []uint16, bm []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BitmapToArray", dst, bm)
	ret0, _ := ret[0].(int)
	return ret0
}

// BitmapToArray indicates an expected call of BitmapToArray.
func (mr *MockOpsMockRecorder) BitmapToArray(dst, bm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BitmapToArray", reflect.TypeOf((*MockOps)(nil).BitmapToArray), dst, bm)
}

// ClearRange mocks base method.
func (m *MockOps) ClearRange(bm []uint64, start, end int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearRange", bm, start, end)
}

// ClearRange indicates an expected call of ClearRange.
func (mr *MockOpsMockRecorder) ClearRange(bm, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRange", reflect.TypeOf((*MockOps)(nil).ClearRange), bm, start, end)
}

// CopyRange mocks base method.
func (m *MockOps) CopyRange(dst, src []uint64, start, end int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CopyRange", dst, src, start, end)
}

// CopyRange indicates an expected call of CopyRange.
func (mr *MockOpsMockRecorder) CopyRange(dst, src, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyRange", reflect.TypeOf((*MockOps)(nil).CopyRange), dst, src, start, end)
}

// DifferenceArrays mocks base method.
func (m *MockOps) DifferenceArrays(dst, a, b []uint16) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DifferenceArrays", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// DifferenceArrays indicates an expected call of DifferenceArrays.
func (mr *MockOpsMockRecorder) DifferenceArrays(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DifferenceArrays", reflect.TypeOf((*MockOps)(nil).DifferenceArrays), dst, a, b)
}

// FlipRange mocks base method.
func (m *MockOps) FlipRange(bm []uint64, start, end int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FlipRange", bm, start, end)
}

// FlipRange indicates an expected call of FlipRange.
func (mr *MockOpsMockRecorder) FlipRange(bm, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlipRange", reflect.TypeOf((*MockOps)(nil).FlipRange), bm, start, end)
}

// HasBitInRange mocks base method.
func (m *MockOps) HasBitInRange(bm []uint64, start, end int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBitInRange", bm, start, end)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBitInRange indicates an expected call of HasBitInRange.
func (mr *MockOpsMockRecorder) HasBitInRange(bm, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBitInRange", reflect.TypeOf((*MockOps)(nil).HasBitInRange), bm, start, end)
}

// IntersectArrays mocks base method.
func (m *MockOps) IntersectArrays(dst, a, b []uint16) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntersectArrays", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntersectArrays indicates an expected call of IntersectArrays.
func (mr *MockOpsMockRecorder) IntersectArrays(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntersectArrays", reflect.TypeOf((*MockOps)(nil).IntersectArrays), dst, a, b)
}

// Intersects mocks base method.
func (m *MockOps) Intersects(a, b []uint64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intersects", a, b)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Intersects indicates an expected call of Intersects.
func (mr *MockOpsMockRecorder) Intersects(a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intersects", reflect.TypeOf((*MockOps)(nil).Intersects), a, b)
}

// OrTo mocks base method.
func (m *MockOps) OrTo(dst, a, b []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrTo", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// OrTo indicates an expected call of OrTo.
func (mr *MockOpsMockRecorder) OrTo(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrTo", reflect.TypeOf((*MockOps)(nil).OrTo), dst, a, b)
}

// Popcount mocks base method.
func (m *MockOps) Popcount(a []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Popcount", a)
	ret0, _ := ret[0].(int)
	return ret0
}

// Popcount indicates an expected call of Popcount.
func (mr *MockOpsMockRecorder) Popcount(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Popcount", reflect.TypeOf((*MockOps)(nil).Popcount), a)
}

// PopcountPrefix mocks base method.
func (m *MockOps) PopcountPrefix(bm []uint64, nbits int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopcountPrefix", bm, nbits)
	ret0, _ := ret[0].(int)
	return ret0
}

// PopcountPrefix indicates an expected call of PopcountPrefix.
func (mr *MockOpsMockRecorder) PopcountPrefix(bm, nbits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopcountPrefix", reflect.TypeOf((*MockOps)(nil).PopcountPrefix), bm, nbits)
}

// SelectBit mocks base method.
func (m *MockOps) SelectBit(bm []uint64, rank int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBit", bm, rank)
	ret0, _ := ret[0].(int)
	return ret0
}

// SelectBit indicates an expected call of SelectBit.
func (mr *MockOpsMockRecorder) SelectBit(bm, rank any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBit", reflect.TypeOf((*MockOps)(nil).SelectBit), bm, rank)
}

// SetRange mocks base method.
func (m *MockOps) SetRange(bm []uint64, start, end int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRange", bm, start, end)
}

// SetRange indicates an expected call of SetRange.
func (mr *MockOpsMockRecorder) SetRange(bm, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRange", reflect.TypeOf((*MockOps)(nil).SetRange), bm, start, end)
}

// UnionArrays mocks base method.
func (m *MockOps) UnionArrays(dst, a, b []uint16) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnionArrays", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// UnionArrays indicates an expected call of UnionArrays.
func (mr *MockOpsMockRecorder) UnionArrays(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnionArrays", reflect.TypeOf((*MockOps)(nil).UnionArrays), dst, a, b)
}

// XorArrays mocks base method.
func (m *MockOps) XorArrays(dst, a, b []uint16) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XorArrays", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// XorArrays indicates an expected call of XorArrays.
func (mr *MockOpsMockRecorder) XorArrays(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XorArrays", reflect.TypeOf((*MockOps)(nil).XorArrays), dst, a, b)
}

// XorTo mocks base method.
func (m *MockOps) XorTo(dst, a, b []uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XorTo", dst, a, b)
	ret0, _ := ret[0].(int)
	return ret0
}

// XorTo indicates an expected call of XorTo.
func (mr *MockOpsMockRecorder) XorTo(dst, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XorTo", reflect.TypeOf((*MockOps)(nil).XorTo), dst, a, b)
}
